FROM docker.io/node:16-alpine AS builder

RUN apk add git

COPY . /app-frontend
WORKDIR /app-frontend

RUN yarn cache clean
RUN yarn install
RUN yarn build:testnet

FROM docker.io/busybox:latest

EXPOSE 3000
COPY --from=builder /app-frontend/dist /build
RUN echo "E404:index.html" > /etc/httpd.conf
ENTRYPOINT ["httpd", "-f", "-p", "0.0.0.0:3000", "-h", "/build", "-c", "/etc/httpd.conf"]
