FROM docker.io/node:16-alpine AS builder
ARG CURRENT_ENV

RUN apk add git

COPY . /bingo-frontend
WORKDIR /bingo-frontend

RUN npm cache clean --force
RUN npm config set registry https://registry.npmjs.org/
RUN yarn cache clean
RUN yarn install
RUN yarn build:dev

FROM nginx:latest

EXPOSE 80
COPY --from=builder /bingo-frontend/dist /app/bingo
COPY nginx.conf /etc/nginx/conf.d/default.conf
