FROM docker.io/node:16-alpine AS builder
ARG CURRENT_ENV

RUN apk add git

COPY . /app-frontend
WORKDIR /app-frontend

RUN yarn cache clean
RUN yarn install
RUN yarn build:dev

FROM jidckii/nginx-geoip2 

EXPOSE 3000
COPY --from=builder /app-frontend/dist /usr/share/nginx/html
COPY --from=builder /app-frontend/public/403.html /usr/share/nginx/html/403.html

RUN sed -i 's/country iso_code/source=$http_x_forwarded_for &/g' /etc/nginx/nginx.conf
COPY --from=builder /app-frontend/nginx_deny_cn.conf /etc/nginx/conf.d/nginx_deny_cn.conf

CMD ["nginx", "-g", "daemon off;"]
