import { preStaticUrl } from '@ui/src'

const preImgPath = preStaticUrl + '/img/ark_index'
export const bannerPath = preImgPath + '/banner'
export const navPath = preImgPath + '/nav'
export const x6Path = preImgPath + '/x6'
export const getPath = preImgPath + '/get'
export const legalPath = preImgPath + '/legal'
export const lrtPath = preImgPath + '/lrt'
export const partnerPath = preImgPath + '/partner'
export const startPath = preImgPath + '/start'
export const timelinePath = preImgPath + '/timeline'
export const whyPath = preImgPath + '/why'
export const faqPath = preImgPath + '/faq'
